### PR TITLE
Add unfulfilled promise rule to the default config

### PR DESCRIPTION
**Pull request by dividedmind**

### CODE REVIEW

**Comment by dividedmind** [comment]
I can't see the build logs because I don't have access to travis. Are the build issues related?

**Comment by kgilpin** [comment]
> I can't see the build logs because I don't have access to travis. Are the build issues related?

[log.txt](https://github.com/getappmap/appmap-js/files/13756991/log.txt)

Here's the log

**Comment by kgilpin** [comment]
> I can't see the build logs because I don't have access to travis. Are the build issues related?

Windows: ```➤ YN0000: [@appland/scanner]: PASS test/scanner/unfulfilledPromise.spec.ts
➤ YN0000: [@appland/scanner]: 
➤ YN0000: [@appland/scanner]: Summary of all failing tests
➤ YN0000: [@appland/scanner]: FAIL test/cli/scan.spec.ts (34.586 s)
➤ YN0000: [@appland/scanner]:   ● scan › watch mode › does not rescan when not needed, but scans every new file @appmap-fixme
➤ YN0000: [@appland/scanner]: 
➤ YN0000: [@appland/scanner]:     ENOENT: no such file or directory, open 'C:\Users\travis\AppData\Local\Temp\Hgj05p\test-2\appmap-findings.json'
➤ YN0000: [@appland/scanner]: 
➤ YN0000: [@appland/scanner]: 
➤ YN0000: [@appland/scanner]: 
➤ YN0000: [@appland/scanner]: 
➤ YN0000: [@appland/scanner]: Test Suites: 1 failed, 44 passed, 45 total
➤ YN0000: [@appland/scanner]: Tests:       1 failed, 153 passed, 154 total
➤ YN0000: [@appland/scanner]: Snapshots:   0 total
➤ YN0000: [@appland/scanner]: Time:        61.597 s
➤ YN0000: [@appland/scanner]: Ran all test suites.
➤ YN0000: [@appland/scanner]: Process exited (exit code 1), completed in 1m 5s```

**Comment by dividedmind** [comment]
> > I can't see the build logs because I don't have access to travis. Are the build issues related?
> 
> [log.txt](https://github.com/getappmap/appmap-js/files/13756991/log.txt)
> 
> Here's the log.

This doesn't seem related, can you re-run? 

> Why don't you have access to Travis?

No idea. A couple months ago it broke for everyone and then some people got access back; I never did.

**Review by kgilpin — APPROVED** [review]

**Comment by kgilpin** [comment]
LGTM but the build is failed

**Comment by kgilpin** [comment]
@dividedmind I think the problem is here: ```➤ YN0000: [@appland/scanner]:   ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
➤ YN0000: [@appland/scanner]:     Attempted to log "Problem processing /tmp/tmp-8206-rj83nG8HHmS4/tmp/appmap/JWT.decode_no_validation/mtime:
➤ YN0000: [@appland/scanner]:      [Error: ENOENT: no such file or directory, open '/tmp/tmp-8206-rj83nG8HHmS4/tmp/appmap/JWT.decode_no_validation/appmap-findings.json'] {
➤ YN0000: [@appland/scanner]:       errno: -2,
➤ YN0000: [@appland/scanner]:       code: 'ENOENT',
➤ YN0000: [@appland/scanner]:       syscall: 'open',
➤ YN0000: [@appland/scanner]:       path: '/tmp/tmp-8206-rj83nG8HHmS4/tmp/appmap/JWT.decode_no_validation/appmap-findings.json'
➤ YN0000: [@appland/scanner]:     }".
➤ YN0000: [@appland/scanner]: 
➤ YN0000: [@appland/scanner]:       57 |
➤ YN0000: [@appland/scanner]:       58 |   constructor(private options: WatchScanOptions) {
➤ YN0000: [@appland/scanner]:     > 59 |     this.queue.error((error, task) => console.warn(`Problem processing ${task}:\n`, error));
➤ YN0000: [@appland/scanner]:          |                                               ^
➤ YN0000: [@appland/scanner]:       60 |   }
➤ YN0000: [@appland/scanner]:       61 |
➤ YN0000: [@appland/scanner]:       62 |   async watch(): Promise<void> {
➤ YN0000: [@appland/scanner]: 
➤ YN0000: [@appland/scanner]:       at console.warn (../../node_modules/jest/node_modules/@jest/console/build/BufferedConsole.js:191:10)
➤ YN0000: [@appland/scanner]:       at src/cli/scan/watchScan.ts:59:47
➤ YN0000: [@appland/scanner]:       at ../../node_modules/async/dist/async.js:1496:46
➤ YN0000: [@appland/scanner]:           at Array.forEach (<anonymous>)
➤ YN0000: [@appland/scanner]:       at trigger (../../node_modules/async/dist/async.js:1496:27)
➤ YN0000: [@appland/scanner]:       at ../../node_modules/async/dist/async.js:1560:25
➤ YN0000: [@appland/scanner]:       at ../../node_modules/async/dist/async.js:327:20```

**Comment by dividedmind** [comment]
> @dividedmind I think the problem is here:
> 
> ```
> ➤ YN0000: [@appland/scanner]:   ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
> ➤ YN0000: [@appland/scanner]:     Attempted to log "Problem processing /tmp/tmp-8206-rj83nG8HHmS4/tmp/appmap/JWT.decode_no_validation/mtime:
> ➤ YN0000: [@appland/scanner]:      [Error: ENOENT: no such file or directory, open '/tmp/tmp-8206-rj83nG8HHmS4/tmp/appmap/JWT.decode_no_validation/appmap-findings.json'] {
> ➤ YN0000: [@appland/scanner]:       errno: -2,
> ➤ YN0000: [@appland/scanner]:       code: 'ENOENT',
> ➤ YN0000: [@appland/scanner]:       syscall: 'open',
> ➤ YN0000: [@appland/scanner]:       path: '/tmp/tmp-8206-rj83nG8HHmS4/tmp/appmap/JWT.decode_no_validation/appmap-findings.json'
> ➤ YN0000: [@appland/scanner]:     }".
> ➤ YN0000: [@appland/scanner]: 
> ➤ YN0000: [@appland/scanner]:       57 |
> ➤ YN0000: [@appland/scanner]:       58 |   constructor(private options: WatchScanOptions) {
> ➤ YN0000: [@appland/scanner]:     > 59 |     this.queue.error((error, task) => console.warn(`Problem processing ${task}:\n`, error));
> ➤ YN0000: [@appland/scanner]:          |                                               ^
> ➤ YN0000: [@appland/scanner]:       60 |   }
> ➤ YN0000: [@appland/scanner]:       61 |
> ➤ YN0000: [@appland/scanner]:       62 |   async watch(): Promise<void> {
> ➤ YN0000: [@appland/scanner]: 
> ➤ YN0000: [@appland/scanner]:       at console.warn (../../node_modules/jest/node_modules/@jest/console/build/BufferedConsole.js:191:10)
> ➤ YN0000: [@appland/scanner]:       at src/cli/scan/watchScan.ts:59:47
> ➤ YN0000: [@appland/scanner]:       at ../../node_modules/async/dist/async.js:1496:46
> ➤ YN0000: [@appland/scanner]:           at Array.forEach (<anonymous>)
> ➤ YN0000: [@appland/scanner]:       at trigger (../../node_modules/async/dist/async.js:1496:27)
> ➤ YN0000: [@appland/scanner]:       at ../../node_modules/async/dist/async.js:1560:25
> ➤ YN0000: [@appland/scanner]:       at ../../node_modules/async/dist/async.js:327:20
> ```

This seems unrelated — looks like a where the directory got removed before the watcher got to it. Is there any reason to think it could be related? Did you try re-running?

**Pull request merged**
