### PR TITLE
Support for Anthropic AI

### LINKED ISSUE #1926: Claude Sonnet 3.5 support in Navie

### PR DESCRIPTION
**Pull request by dividedmind**
# Synopsis

```console
$ export ANTHROPIC_API_KEY=sk-ant-api03-8EU...
$ export APPMAP_NAVIE_MODEL=claude-3-5-sonnet-20240620
$ appmap navie hello
```

# Add Support for Anthropic AI API

This pull request adds support for the Anthropic AI API as an alternative to OpenAI for the completion service. The main changes include:

1. Created a new `AnthropicCompletionService` class to handle Anthropic API interactions.
2. Implemented a `CompletionServiceFactory` to dynamically choose between OpenAI and Anthropic backends based on environment variables.
3. Refactored the existing OpenAI completion service into a separate `OpenAICompletionService` class.
4. Updated dependencies to include Anthropic SDK and newer versions of LangChain and related packages.
5. Added new environment variables `ANTHROPIC_API_KEY` and `APPMAP_NAVIE_COMPLETION_BACKEND` for configuration.
6. Created new test files for Anthropic completion service and the factory.
7. Updated existing tests and imports to reflect the new structure.

To use the Anthropic backend, set the `ANTHROPIC_API_KEY` environment variable and optionally set `APPMAP_NAVIE_COMPLETION_BACKEND` to "anthropic". The system will default to Anthropic if the API key is present.

This change provides more flexibility in choosing AI providers and allows for easy switching between OpenAI and Anthropic backends.

Fixes #1926 

# Improvements to AppMap JS Project

This pull request includes several improvements to the AppMap JS project:

1. Added a build task for Navie in VSCode:
   - Created a new `tasks.json` file in the `packages/navie/.vscode/` directory.
   - Set up a TypeScript watch task for automatic compilation.

2. Deduplicated langchain versions:
   - Updated the langchain version in `packages/cli/package.json` from `^0.1.25` to `^0.2.12`.
   - This change aligns the langchain version used in the CLI package with the version used in the Navie package.
   - Removed numerous optional dependencies related to AWS, Azure, and other services from the yarn.lock file, simplifying the project's dependency tree.

These changes should improve the development experience for the Navie package and ensure consistency in the langchain library usage across the project. The deduplication of dependencies will also help in maintaining a cleaner and more manageable package structure.

### CODE REVIEW

**Review by kgilpin — APPROVED** [review]

**Comment by kgilpin** [comment]
A commit comment may need to be `feat:` to trigger the release tagging.

**Comment by petecheslock** [comment]
@dividedmind when using the @generate command in Navie with anthropic I got the following error:

```
Stack trace: Error: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages: first message must use the \"user\" role"}}
    at APIError.generate (/Users/petecheslock/repos/appmap-js/node_modules/@anthropic-ai/sdk/error.js:40:20)
    at Anthropic.makeStatusError (/Users/petecheslock/repos/appmap-js/node_modules/@anthropic-ai/sdk/core.js:263:33)
    at Anthropic.makeRequest (/Users/petecheslock/repos/appmap-js/node_modules/@anthropic-ai/sdk/core.js:306:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (/Users/petecheslock/repos/appmap-js/node_modules/p-retry/index.js:50:12)
```

Full stack trace https://gist.github.com/petecheslock/763b730bb26de9a876d939689daa68c7

**Comment by petecheslock** [comment]
Here is another example.  

question: 
```
@diagram how this interaction will look like when the code is complete
```


```
[local-navie] Processing question cca95f31-ebe7-4d29-a387-36c5572e6d57 in thread bdf67bea-9c0a-4cf5-a770-199bb82afc47
Using model claude-3-5-sonnet-20240620
Using Anthropic AI backend
Explain received context request: projectInfo
Project info obtained
Handling exception: BadRequestError: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages: first message must use the \"user\" role"}}
    at APIError.generate (/Users/petecheslock/repos/appmap-js/node_modules/@anthropic-ai/sdk/error.js:40:20)
    at Anthropic.makeStatusError (/Users/petecheslock/repos/appmap-js/node_modules/@anthropic-ai/sdk/core.js:263:33)
    at Anthropic.makeRequest (/Users/petecheslock/repos/appmap-js/node_modules/@anthropic-ai/sdk/core.js:306:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (/Users/petecheslock/repos/appmap-js/node_modules/p-retry/index.js:50:12) {
  status: 400,
  headers: {
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8b2a33d9ab443b8d-BOS',
    connection: 'keep-alive',
    'content-length': '120',
    'content-type': 'application/json',
    date: 'Tue, 13 Aug 2024 16:50:09 GMT',
    'request-id': 'req_01HGhQhon3faqk2QMf2cvrZb',
    server: 'cloudflare',
    via: '1.1 google',
    'x-cloud-trace-context': '20f8f8c14aea682da5eb2ec8ff083e99',
    'x-robots-tag': 'none',
    'x-should-retry': 'false'
  },
  error: {
    type: 'error',
    error: {
      type: 'invalid_request_error',
      message: 'messages: first message must use the "user" role'
    }
  },
  attemptNumber: 1,
  retriesLeft: 6
}
Stack trace: Error: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages: first message must use the \"user\" role"}}
    at APIError.generate (/Users/petecheslock/repos/appmap-js/node_modules/@anthropic-ai/sdk/error.js:40:20)
    at Anthropic.makeStatusError (/Users/petecheslock/repos/appmap-js/node_modules/@anthropic-ai/sdk/core.js:263:33)
    at Anthropic.makeRequest (/Users/petecheslock/repos/appmap-js/node_modules/@anthropic-ai/sdk/core.js:306:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (/Users/petecheslock/repos/appmap-js/node_modules/p-retry/index.js:50:12)
```

**Comment by dividedmind** [comment]
@petecheslock the recent changes should have fixed the problem, can you give it another try?
@dustinbyrne I had to modify some history handling, can you give it a quick look for a sanity check?

Thanks!

**Review by dustinbyrne — APPROVED** [review]

**Pull request merged**
