### PR TITLE
Flamegraph tweak

### PR DESCRIPTION
**Pull request by lachrist**
Tweak the flamegraph to incorporate changes discussed in the standup meeting of the 20th of June.

What is missing:
- Border alignment championed by @dividedmind. I'm still fuzzy on that.
- Duration display on the left detail panel.
- Removing the rest boxes (I only greyed them because I was too sad to completely remove them)

### CODE REVIEW

**Comment by brikelly** [comment]
Here are some AppMaps showing the issues with the dark empty event boxes and the disembodied events:
[solidus-maps.zip](https://github.com/getappmap/appmap-js/files/11824514/solidus-maps.zip)

Both were generated from the Solidus app.

**Comment by brikelly** [comment]
Also, the mouse "wheel" action should influence the zoom level. My Apple magic mouse will zoom the Trace and Dependency views in and out if I swipe my finger up or down, and I think we'd like the same behavior in flame graph.

**Comment by kgilpin** [comment]
> Also, the mouse "wheel" action should influence the zoom level. My Apple magic mouse will zoom the Trace and Dependency views in and out if I swipe my finger up or down, and I think we'd like the same behavior in flame graph.

This seems like a non blocking issue

**Comment by brikelly** [comment]
Yeah the mouse action is not a blocking issue.

**Comment by evlawler** [comment]
Please get this moving

**Comment by lachrist** [comment]
@brikelly I see the issue I will fix this asap tomorrow.

**Comment by lachrist** [comment]
@brikelly I fixed the issue.

**Comment by kgilpin** [comment]
> @brikelly I fixed the issue.

Thanks, Laurent. Is this all done, then?

**Review by dustinbyrne — APPROVED** [review]

**Pull request merged**
