### PR TITLE
fix: Adjust the first line of a patch when it has 0 indent

### PR DESCRIPTION
**Pull request by kgilpin**
Fixes https://github.com/getappmap/appmap-js/issues/2095

### CODE REVIEW

**Comment by dividedmind** [comment]
I don't think this actually works... let me double check. I had a simpler solution in mind, if this doesn't work then I'll try mine, ok?

**Comment by kgilpin** [comment]
Yeah, it doesn't. Try your way.

**Comment by dividedmind** [comment]
> Yeah, it doesn't. Try your way.

I will. I pushed a commit that makes the tests more robust so it's apparent that it doesn't work.

**Comment by dividedmind** [comment]
Another approach at #2100

**Pull request closed without merging**
