### PR TITLE
Incorporate docs from mainline branch

### PR DESCRIPTION
**Pull request by petecheslock**
Here's what i did

1) create new branch off the `main` branch
2) checkout mainline of appmap website docs
3) `rsync --delete -av ../applandinc.github.io/_docs/* docs/`
4) Opened this PR.

### CODE REVIEW

**Review by kgilpin — APPROVED** [review]

**Comment by kgilpin** [comment]
Ok and does it seem sane to you?

**Comment by kgilpin** [comment]
The base of this PR can be Main

**Comment by petecheslock** [comment]
ok great - let me make those adjustments.

**Comment by petecheslock** [comment]
Ok i think this is good to go now - the branch base is `main` incorporated the same changes.  Look right?

**Comment by kgilpin** [comment]
Yeah - you know the content best but lgtm

**Comment by petecheslock** [comment]
Good to go - also `next-doc` is reset back to mainline.

**Pull request merged**
