### PR TITLE
fix: More reliable polling in index --watch

### PR DESCRIPTION
**Pull request by dividedmind**
Instead of using chokidar polling mode, periodically rescan the directory with glob to find appmaps. This is more reliable and avoids many corner cases of chokidar.

### CODE REVIEW

**Review by apotterri — APPROVED** [review]
Code looks good to me. As long as @kgilpin is on board with this change, I'd say we should go ahead with it.

**Comment by ahtrotta** [comment]
I'm getting a ton of test failures in Windows, but most of them aren't relevant to this PR (I'll open a separate issue). Here are the ones that are:

image

image

**Comment by ahtrotta** [comment]
I just built this and ran it manually in Windows, and it seems to work well :)

**Comment by ahtrotta** [comment]
I figured out the problem with the `rejects appmaps that are too large` test. You just need to change lines 24 & 25 in `tests/unit/fingerprinter/fingerprint.spec.ts` to use `await`:

```
await file.write('{}', 500 * 1000 * 1000);
await file.close();
```

**Comment by dividedmind** [comment]
> I figured out the problem with the `rejects appmaps that are too large` test. You just need to change lines 24 & 25 in `tests/unit/fingerprinter/fingerprint.spec.ts` to use `await`:
> 
> ```
> await file.write('{}', 500 * 1000 * 1000);
> await file.close();
> ```

Good catch, thanks! The telemetry failure is unrelated, but I've seen it too. I know what the problem is, but I haven't figured out a good fix yet. Fortunately it doesn't seem to occur in CI.

**Review by ahtrotta — APPROVED** [review]
Looks good to me!

**Pull request merged**
