### PR TITLE
feat: Update PR change report

### PR DESCRIPTION
**Pull request by kgilpin**
Update the change report that's generated for pull requests.

This PR refactors the existing monolithic [Handlebars template](https://github.com/getappmap/appmap-js/blob/main/packages/cli/resources/change-report.hbs) into a [pair of templates for each report section](https://github.com/getappmap/appmap-js/tree/feat/refactor-change-report/packages/cli/resources/change-report). 

A [preprocessor](https://github.com/getappmap/appmap-js/blob/feat/refactor-change-report/packages/cli/src/cmds/compare-report/Preprocessor.ts) is now used to determine when there are many changes in the PR, and emit only a subset of those details to the report. This will prevent AppMap from breaking the PR by submitting a description greater than the limit of 64kb, and it will also be kinder to the user as well.

The report also includes some nice updates, such as:

* [Description of what a "breaking change" is](https://github.com/getappmap/appmap-js/blob/feat/refactor-change-report/packages/cli/tests/unit/compareReport/expectedReport.md.txt#L110)
* [Using the finding name as the markdown section name](https://github.com/getappmap/appmap-js/blob/feat/refactor-change-report/packages/cli/tests/unit/compareReport/expectedReport.md.txt#L179)
* [Better formatting of the finding description](https://github.com/getappmap/appmap-js/blob/feat/refactor-change-report/packages/cli/tests/unit/compareReport/expectedReport.md.txt#L179)
* [Link to the rule definition](https://github.com/getappmap/appmap-js/blob/feat/refactor-change-report/packages/cli/tests/unit/compareReport/expectedReport.md.txt#L189)
* [More user-friendly AppMap link names](https://github.com/getappmap/appmap-js/blob/feat/refactor-change-report/packages/cli/tests/unit/compareReport/expectedReport.md.txt#L309)

## Sample report

[expectedReport.md.zip](https://github.com/getappmap/appmap-js/files/12675715/expectedReport.md.zip)

### CODE REVIEW

**Review by brikelly — COMMENTED** [review]
It looks like there are anchor links to the last 2 sections in the map, but not for the first 2. That means that if someone clicks on the links in the summary table, the first 2 (Failed tests and API changes) don't scroll the report down to the right section.

So you'll probably want to add this for those sections:
`<h2 id="failed-tests">Failed Tests</h2>`

Other new changes to the report look great.

**Comment by dustinbyrne** [comment]
I've looked through this and it looks good. With the missing header anchors @brikelly mentioned and the test failures addressed I see no other reason this can't be approved. :+1:

**Review by brikelly — APPROVED** [review]
Did a cursory review (i.e. I didn't test it out), but looks good

**Comment by kgilpin** [comment]
Moving to Draft in the meantime.

**Pull request merged**
