### PR TITLE
1144 - Sign-in test flow 1

### LINKED ISSUE #1144: Sign-in UX testing - Flow 1
[Notion -> ](https://www.notion.so/appmap/Flow-Test-1-a0ea52a9ed1947ee99d30160c273d828?pvs=4)
[Figma -> ](https://www.figma.com/file/vevGAGm1cr4UwTulow1sfo/sign-in?node-id=2%3A134&t=Lcz85QhpwVEf5DvP-1)

Image

### PR DESCRIPTION
**Pull request by typaulhus**
- Closes #1144 
- Updates sign-in flow for UX flow test 1
[View in Chromatic](https://5fe18baf66f2280021e634d0-upfrqhucci.chromatic.com/?path=/story/pages-vs-code--sign-in)
Screenshot 2023-04-27 at 9 57 12 AM

[Notion ->](https://www.notion.so/appmap/Flow-Test-1-a0ea52a9ed1947ee99d30160c273d828?pvs=4)
[Figma -> ](https://www.figma.com/file/vevGAGm1cr4UwTulow1sfo/sign-in?node-id=2%3A134&t=Lcz85QhpwVEf5DvP-1)

### CODE REVIEW

**Comment by Daniel-Warner-X** [comment]
@typaulhus the current sign-in page is performing really well, so I think we should scale back this change a little bit...
1. Use the existing language:
image
2. Keep the feature links separated:
image
3. Keep the CTA as one button with the same label "sign in": 
image
4. Keep this language in the data residency statement:
image

So that means the only thing we are adding is the 'Not ready to sign in' secondary action, and the resulting new options. 
image

Also, the build is failing so we're not getting a storybook link on this PR.

**Review by Daniel-Warner-X — CHANGES_REQUESTED** [review]
@typaulhus the current sign-in page is performing really well, so I think we should scale back this change a little bit...
1. Use the existing language:
image
2. Keep the feature links separated:
image
3. Keep the CTA as one button with the same label "sign in": 
image
4. Keep this language in the data residency statement:
image

So that means the only thing we are adding is the 'Not ready to sign in' secondary action, and the resulting new options. 
image

Also, the build is failing so we're not getting a storybook link on this PR.

**Review by Daniel-Warner-X — CHANGES_REQUESTED** [review]
@typaulhus the 'Not ready...' cta feels really prominent. Please make it not bold, centered, and under the data residency statement, like this... 
image

Also, please update the wording based on the mockup above. Thanks!

**Comment by typaulhus** [comment]
> @typaulhus the 'Not ready...' cta feels really prominent. Please make it not bold, centered, and under the data residency statement, like this... image
> 
> Also, please update the wording based on the mockup above. Thanks!

I made these edits. We just need the links for the sample AppMap & new video.

**Review by Daniel-Warner-X — DISMISSED** [review]
Another wording update for the Slack link... 
image
Thanks @typaulhus

**Review by ahtrotta — APPROVED** [review]

**Pull request merged**
